<?php
/**
 * @description Contact form widget template
 * @author      C. M. de Picciotto <d3p1@d3p1.dev> (https://d3p1.dev/)
 */
?>

<?php
/**
 * @var \D3p1\ContactForm\Block\Widget\Form $block
 */
?>

<div class="contact-form-widget-container">
    <form class="form contact" action="#" id="contact-form" method="post">
        <fieldset class="fieldset">
            <legend class="legend title">
                <span><?= $block->escapeHtml(__('Contact')) ?></span>
            </legend>

            <div class="fields content">
                <div class="input-field">
                    <input type="text" name="name" id="name" class="input-text" title="<?= $block->escapeHtmlAttr(__('Name')) ?>"/>
                    <label for="name"><?= $block->escapeHtml(__('Name')) ?></label>
                </div>

                <div class="input-field">
                    <input type="email" name="email" id="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>"/>
                    <label for="email"><?= $block->escapeHtml(__('Email')) ?></label>
                </div>

                <div class="input-field">
                    <input type="text" name="telephone" id="telephone" class="input-text" title="<?= $block->escapeHtmlAttr(__('Phone number')) ?>"/>
                    <label for="telephone"><?= $block->escapeHtml(__('Phone number')) ?></label>
                </div>

                <div class="input-field">
                    <textarea name="comment" id="comment" class="textarea" title="<?= $block->escapeHtmlAttr(__('What’s on your mind?')) ?>"></textarea>
                    <label for="comment"><?= $block->escapeHtml(__('What’s on your mind?')) ?></label>
                </div>

                <input type="hidden" name="isAjax" id="isAjax" value="1"/>
            </div>
        </fieldset>

        <?= $block->getFormAdditionalInfoHtml() ?>

        <div class="actions-toolbar">
            <div class="primary">
                <button type="submit" title="<?= $block->escapeHtmlAttr(__('Submit')) ?>" class="action submit primary">
                    <span class="text"><?= $block->escapeHtml(__('Submit')) ?></span>
                </button>
            </div>
        </div>
    </form>
</div>

<script>
// <![CDATA[
require(['jquery', 'Magento_Ui/js/modal/alert'], function($, alert) {
    $(document).ready(function() {
        var form = $('#contact-form');

        form.submit(function(event) {
            if ($(this).valid()) {
                event.preventDefault();
                var data = $(this).serialize();
                $.ajax({
                    showLoader: true,
                    url       : '<?php echo $block->getContactUrl() ?>',
                    data      : data,
                    type      : 'POST',
                    dataType  : 'json'
                }).done(function (data) {
                    alert({
                        title   : '<?php echo __('Contact') ?>',
                        content : data['message'],
                        autoOpen: true,
                        focus   : 'none'
                    });
                });
            }
        });
    });
});
// ]]>
</script>
